# Generated by Django 5.0.6 on 2024-05-31 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_buildingmaterials_views'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='members',
        ),
        migrations.AddField(
            model_name='dialog',
            name='member_from',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs_received', to='main.profile', verbose_name='Участник с которым начали диалог'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialog',
            name='member_to',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs_started', to='main.profile', verbose_name='Участник начавший диалог'),
            preserve_default=False,
        ),
    ]
