# Generated by Django 5.0.2 on 2024-03-11 20:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True, verbose_name='Название материала')),
                ('description', models.TextField(max_length=256, null=True, verbose_name='Описание материала')),
                ('image', models.ImageField(default='chto.png', upload_to='profile_pics')),
                ('pdf', models.FileField(null=True, upload_to='luckych/uploads', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('price', models.IntegerField(default=0, null=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
