# Generated by Django 4.2.11 on 2024-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingmaterials',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
