# Generated by Django 4.2.11 on 2024-04-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_buildingmaterials_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingmaterials',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
