# Generated by Django 4.2.11 on 2024-04-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_buildingmaterials_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingmaterials',
            name='pdf',
        ),
    ]
