# Generated by Django 4.2.11 on 2024-04-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_buildingmaterials_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingmaterials',
            options={'ordering': ('title',)},
        ),
        migrations.AlterIndexTogether(
            name='buildingmaterials',
            index_together={('id', 'slug')},
        ),
    ]
