# Generated by Django 4.2.11 on 2024-04-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_buildingmaterials_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingmaterials',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='buildingmaterials',
            index_together=set(),
        ),
    ]
