# Generated by Django 4.2.11 on 2024-04-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_buildingmaterials_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmaterials',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
