# Generated by Django 4.2.11 on 2024-04-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingmaterials',
            name='likes',
            field=models.ManyToManyField(related_name='liked_materials', through='main.Like', to='main.profile'),
        ),
    ]
