# Generated by Django 4.2.11 on 2024-04-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_category_buildingmaterials_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
